package: animatedlogin
author: KLXM Crossmedia GmbH, Moers
version: 1.0.0
supportpage: https://github.com/KLXM/animated_login
load: late
requires:
    redaxo: '^5.12.0'
    php:
        version: '>=7, <9'
