package: animatedlogin
version: 2.0.0
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/addon_key
load: late
requires:
    redaxo: '^5.12.0'
    php:
        version: '>=7, <9'
